### ISSUE TITLE
Improve module logging

### ISSUE THREAD

**Issue by mirsella** [sweihub/log2#2]
Hello ! I love your crate !

if logging from a module name `foo` using the `mod.rs` module declaration inside a `foo` directory, log2 will output like this `[2024-02-06 21:15:24.869] [TRACE] foo/mod:`.
imo it's not very nice, and instead should be just `foo`.

tell me what you think !

thanks

**Comment by sweihub** [comment]
Hi

Sorry for late reply due to my internet issues.

Good feedback, I just missed the mod.rs convention, I’ll fix it shortly, thanks!

**Comment by sweihub** [comment]
Hello @mirsella 

The issue was fixed in v0.1.11, please do `cargo update log2`.
